### ISSUE TITLE
MySQL connection from Kubernetes engine

### ISSUE THREAD

**Issue by StephenKing** [TYPO3-infrastructure/kubernetes-infra#17]
needs google cloud SQL proxy: https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine

**Comment by sgrossberndt** [comment]
Added HackMD using Google Cloud SQL as an example

https://github.com/TYPO3-infrastructure/kubernetes-infra/commit/70582538619f412a3ae24c41ddc2006e35643339
